
Import('*')

if not env['BUILD_VECTOR_ENGINE']:
    SimObject('MemUnitReadTiming.py', sim_objects=['MemUnitReadTiming'])
    SimObject('MemUnitWriteTiming.py', sim_objects=['MemUnitWriteTiming'])
    SimObject('VectorMemUnit.py', sim_objects=['VectorMemUnit'])

    Source('write_timing_unit.cc')
    Source('read_timing_unit.cc')
    Source('vector_mem_unit.cc')


    DebugFlag('MemUnitWriteTiming')
    DebugFlag('MemUnitReadTiming')
    DebugFlag('VectorMemUnit')

    CompoundFlag('VectorMem',
        [ 'VectorMemUnit','MemUnitWriteTiming', 'MemUnitReadTiming' ])
